# Generated by tools/publish/scripts/homebrew_formula.py.
# Unsigned alpha release; desktop/minimum-system acceptance pending.
class UsagestatAlpha < Formula
  desc "Scriptable CLI for local agent usage data"
  homepage "https://github.com/hashimkarim/usagestat"
  version "2.0.0-alpha.1"
  license "MIT"
  on_linux do
    conflicts_with "usagestat", because: "both install the usagestat commands"
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.1/usagestat-linux-aarch64.tar.gz"
      sha256 "b6f7cc9bd787453cf1e7f12d883d227490ba9cb5dc4713ffa0d4ba9725f73a04"
    else
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.1/usagestat-linux-x86_64.tar.gz"
      sha256 "f18b97f82d6448b79cb64f93ebfe1851daf0733bdfe3bc7f82563a899f7e5284"
    end
  end

  on_macos do
    depends_on macos: :big_sur
    if Hardware::CPU.arm?
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.1/usagestat-macos-aarch64.tar.gz"
      sha256 "5c471ed6aae6073c5e801b671b7035a45238a88866490751a60cf6f7aef07e49"
    else
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.1/usagestat-macos-x86_64.tar.gz"
      sha256 "8b5424939928ae0a65cf800a3315cea1141ef2f1b899d6cf82d7409bcd797cf7"
    end
  end

  def install
    bin.install "usagestat", "usagestatd"
    (share/"usagestat").install "plugins", "LICENSE"
  end

  def caveats
    <<~EOS
      Enable login startup explicitly with: usagestat daemon enable
      The usagestat CLI owns startup registration; no brew services entry is installed.
      Before removing a managed installation, run: usagestat daemon unregister
      Configuration, history, and credentials are retained when uninstalling.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/usagestat --version")
    assert_match version.to_s, shell_output("#{bin}/usagestatd --version")
    ENV["USAGESTAT_CONFIG_DIR"] = (testpath/"config").to_s
    ENV["USAGESTAT_DATA_DIR"] = (testpath/"data").to_s
    providers = JSON.parse(shell_output("#{bin}/usagestat --json list"))
    assert providers.any? { |provider| provider["id"] == "codex" }
    assert_path_exists share/"usagestat/plugins/codex/plugin.json"
  end
end
