# Generated by tools/publish/scripts/homebrew_formula.py.
# Unsigned alpha release; desktop/minimum-system acceptance pending.
class UsagestatAlpha < Formula
  desc "Scriptable CLI for local agent usage data"
  homepage "https://github.com/hashimkarim/usagestat"
  version "2.0.0-alpha.3"
  license "MIT"
  on_linux do
    conflicts_with "usagestat", because: "both install the usagestat commands"
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.3/usagestat-linux-aarch64.tar.gz"
      sha256 "f2eb9820b8ad95a0a843ebb4ef3104cfa35c6a5bd3d99eb75ad78a0fc1101d73"
    else
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.3/usagestat-linux-x86_64.tar.gz"
      sha256 "e53e36b9001caf5b0cdd4de3acb077dcddaa41a7f2acd91f5d81682ab3b98672"
    end
  end

  on_macos do
    depends_on macos: :big_sur
    if Hardware::CPU.arm?
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.3/usagestat-macos-aarch64.tar.gz"
      sha256 "ad94df5267340ff56c20f2605151b68276093ca42639eca71db857591d55e07b"
    else
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.3/usagestat-macos-x86_64.tar.gz"
      sha256 "f1690d1d0fc6f9cd784682128ff675ab4e943b21f5a892a33384eb6b194305f7"
    end
  end

  def install
    bin.install "usagestat", "usagestatd"
    (share/"usagestat").install "plugins", "LICENSE"
  end

  def caveats
    <<~EOS
      Enable login startup explicitly with: usagestat daemon enable
      The usagestat CLI owns startup registration; no brew services entry is installed.
      Before removing a managed installation, run: usagestat daemon unregister
      Configuration, history, and credentials are retained when uninstalling.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/usagestat --version")
    assert_match version.to_s, shell_output("#{bin}/usagestatd --version")
    ENV["USAGESTAT_CONFIG_DIR"] = (testpath/"config").to_s
    ENV["USAGESTAT_DATA_DIR"] = (testpath/"data").to_s
    providers = JSON.parse(shell_output("#{bin}/usagestat --json list"))
    assert providers.any? { |provider| provider["id"] == "codex" }
    assert_path_exists share/"usagestat/plugins/codex/plugin.json"
  end
end
